name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Tests
      run: |
            pwd 
            ls
            go get -u github.com/admd/hub_xmlrpc_api
    - name: Build
      run: go build main.go
   
